import SwiftUI
import AppIntents
#if canImport(WidgetKit)
import WidgetKit
#endif

extension DashboardCard {
    /// Whether to draw the "SAMPLE" badge. Demo data stays labelled in normal
    /// use; Settings → Developer can suppress the labelling so the marketing
    /// screenshots show the product rather than the disclaimer. Lives here
    /// rather than on the model so the app and the widget extension, which both
    /// render through this file, cannot disagree.
    var showsSampleBadge: Bool {
        isSample && !SharedSettings.hideSampleIndicators
    }
}

public enum CardRenderContext {
    case app
    case widgetSmall
    case widgetMedium
    case widgetLarge
    case accessoryRectangular
    case accessoryCircular
    case accessoryInline
}

public enum CardRenderDensity: String, Hashable, Sendable {
    case automatic
    case compact
    case detailed
}

public struct CardView: View {
    public let card: DashboardCard
    public let context: CardRenderContext
    public let density: CardRenderDensity
    private let appActionHandler: ((ActionDefinition) -> Void)?
    #if canImport(WidgetKit)
    @Environment(\.widgetRenderingMode) private var widgetRenderingMode
    #endif

    public init(
        card: DashboardCard,
        context: CardRenderContext = .app,
        density: CardRenderDensity = .automatic,
        appActionHandler: ((ActionDefinition) -> Void)? = nil
    ) {
        self.card = card
        self.context = context
        self.density = density
        self.appActionHandler = appActionHandler
    }

    public var body: some View {
        switch context {
        case .accessoryInline:
            inlineView
        case .accessoryCircular:
            circularView
        case .accessoryRectangular:
            rectangularView
        case .widgetSmall:
            smallView
        case .widgetMedium:
            mediumView
        case .widgetLarge:
            largeView
        case .app:
            appView
        }
    }

    private var header: some View {
        HStack(spacing: 6) {
            if let icon = card.icon {
                Image(systemName: icon)
                    .font(.caption)
                    .foregroundStyle(card.status.tint)
            }
            Text(card.title)
                .font(.caption)
                .fontWeight(.medium)
                .lineLimit(1)
            if card.isFromGuestLink { guestBadge }
            if card.showsSampleBadge { sampleBadge }
            Spacer(minLength: 0)
            if let statusIcon = card.statusIcon {
                Image(systemName: statusIcon)
                    .font(.caption)
                    .foregroundStyle(card.status.tint)
            }
            StatusBadge(status: card.status, compact: true)
        }
    }

    /// Marks a card followed through someone else's shared link, so a card on
    /// the Home Screen is never mistaken for one of your own. Unlike the sample
    /// badge this is not suppressible: it states whose data this is, which is
    /// not a disclaimer that can be turned off for a screenshot.
    private var guestBadge: some View {
        Image(systemName: "link")
            .font(.system(size: 9, weight: .bold))
            .padding(4)
            .background(Circle().fill(Color.secondary.opacity(0.18)))
            .foregroundStyle(.secondary)
            .accessibilityLabel("Shared with you")
            .fixedSize()
    }

    /// Marks cards generated by `SampleDataFactory` so demo data is never
    /// mistaken for something an agent published — including on the Home
    /// Screen, where the widget is all the user sees.
    private var sampleBadge: some View {
        Text("SAMPLE")
            .font(.system(size: 9, weight: .bold))
            .padding(.horizontal, 5)
            .padding(.vertical, 2)
            .background(Capsule().fill(Color.secondary.opacity(0.18)))
            .foregroundStyle(.secondary)
            .lineLimit(1)
            .fixedSize()
    }

    private var bigValue: some View {
        HStack(alignment: .firstTextBaseline, spacing: 2) {
            Text(card.value ?? "—")
                .font(.system(size: 34, weight: .semibold, design: .rounded))
                .minimumScaleFactor(0.6)
                .lineLimit(1)
            if let unit = card.unit {
                Text(unit)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var smallView: some View {
        VStack(alignment: .leading, spacing: 6) {
            header
            Spacer(minLength: 0)
            switch card.template {
            case .progress:
                if let p = card.progressValue {
                    if card.progressValueIsLabel { bigValue }
                    ProgressRow(progress: p, label: card.subtitle)
                } else {
                    bigValue
                }
            case .action:
                actionSummary
                actionButtons(max: 1)
            case .list:
                listRows(max: 3)
            case .chart:
                chartHeadline
                sparkline(height: 30, lineWidth: 1.8)
            case .history:
                chartHeadline
                statusStrip(limit: 10, height: 12)
            case .breakdown:
                chartHeadline
                compositionBar(height: 12)
            case .summary:
                bigValue
                if let subtitle = card.subtitle {
                    Text(subtitle)
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
            }
            if card.template != .action {
                actionButtons(max: density == .compact ? 0 : 1)
            }
        }
        .padding(8)
    }

    private var mediumView: some View {
        VStack(alignment: .leading, spacing: 6) {
            header
            switch card.template {
            case .list:
                listRows(max: density == .detailed ? 4 : 3)
            case .action:
                actionSummary
                actionButtons(max: density == .compact ? 1 : 2)
            case .progress:
                if let p = card.progressValue {
                    ProgressRow(progress: p, label: card.subtitle)
                }
                bigValue
            case .chart:
                chartHeadline
                sparkline(height: density == .compact ? 32 : 46)
            case .history:
                chartHeadline
                statusStrip(limit: density == .compact ? 12 : 14, height: 14)
            case .breakdown:
                chartHeadline
                compositionBar(height: 14)
                breakdownLegend(max: density == .compact ? 0 : 2)
            case .summary:
                HStack(alignment: .top) {
                    VStack(alignment: .leading, spacing: 4) {
                        bigValue
                        if density != .compact, let subtitle = card.subtitle {
                            Text(subtitle)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                    Spacer()
                }
            }
            if card.template != .action {
                actionButtons(max: density == .compact ? 1 : 2)
            }
            Spacer(minLength: 0)
            if density != .compact {
                Text(card.updatedAt, style: .relative)
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
        }
        .padding(10)
    }

    private var largeView: some View {
        VStack(alignment: .leading, spacing: 8) {
            header
            switch card.template {
            case .list:
                listRows(max: density == .compact ? 4 : 6)
            case .action:
                actionSummary
                actionButtons(max: density == .compact ? 2 : 4)
            case .chart:
                chartHeadline
                sparkline(height: density == .compact ? 60 : 90)
            case .history:
                chartHeadline
                statusStrip(limit: 20, height: 16)
                listRows(max: density == .compact ? 2 : 4)
            case .breakdown:
                chartHeadline
                compositionBar(height: 16)
                breakdownLegend(max: density == .compact ? 3 : 5)
            case .summary, .progress:
                bigValue
                if let subtitle = card.subtitle {
                    Text(subtitle)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                if let p = card.progressValue {
                    ProgressRow(progress: p, label: nil)
                }
            }
            if card.template != .action {
                actionButtons(max: density == .compact ? 2 : 4)
            }
            Spacer(minLength: 0)
            if density != .compact {
                Text("Updated \(card.updatedAt, style: .relative) ago")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
        }
        .padding(12)
    }

    private var rectangularView: some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack(spacing: 4) {
                if let icon = card.icon { Image(systemName: icon) }
                Text(card.title).font(.caption2).fontWeight(.medium)
                if card.isFromGuestLink { guestBadge }
            if card.showsSampleBadge { sampleBadge }
                Spacer(minLength: 0)
                if let statusIcon = card.statusIcon {
                    Image(systemName: statusIcon).font(.caption2)
                }
            }
            Text(card.value ?? card.status.label)
                .font(.headline)
            if card.template == .breakdown, let items = card.items, !items.isEmpty {
                CompositionBarView(items: items, tint: .primary, height: 8)
            } else if card.template == .history, let items = card.items, !items.isEmpty {
                StatusStripView(items: items, limit: 12, height: 8)
            } else if card.template == .chart, let chart = card.chart, chart.isRenderable {
                // The accessory families render monochrome, so the tint would
                // be flattened anyway; an unfilled line stays legible.
                SparklineView(chart: chart, tint: .primary, lineWidth: 1.5, showsArea: false)
                    .frame(height: 14)
            } else if let subtitle = card.subtitle {
                Text(subtitle).font(.caption2).foregroundStyle(.secondary).lineLimit(1)
            }
        }
    }

    @ViewBuilder
    private var circularView: some View {
        #if os(tvOS)
        EmptyView()
        #else
        Gauge(value: card.progressValue ?? 0) {
            if let icon = card.icon { Image(systemName: icon) }
        } currentValueLabel: {
            Text(card.value ?? "—").font(.caption).lineLimit(1)
        }
        .gaugeStyle(.accessoryCircular)
        #endif
    }

    private var inlineView: some View {
        HStack(spacing: 4) {
            if let icon = card.icon { Image(systemName: icon) }
            Text("\(card.title): \(card.value ?? card.status.label)\(card.unit.map { " \($0)" } ?? "")")
        }
    }

    private var appView: some View {
        VStack(alignment: .leading, spacing: 16) {
            appHeader
            appContent

            if density != .compact {
                appControls

                Label(
                    card.updatedAt.formatted(.relative(presentation: .named)),
                    systemImage: "clock"
                )
                .font(.caption)
                .foregroundStyle(.tertiary)
            }
        }
        .padding(20)
        .background(appBackground)
        .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))
        .overlay {
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(Color.primary.opacity(0.08), lineWidth: 1)
        }
        .shadow(color: Color.black.opacity(0.08), radius: 16, x: 0, y: 8)
    }

    private var appHeader: some View {
        HStack(spacing: 12) {
            ZStack {
                Circle()
                    .fill(card.status.tint.opacity(0.16))
                Image(systemName: card.icon ?? "square.grid.2x2")
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundStyle(card.status.tint)
            }
            .frame(width: 36, height: 36)

            Text(card.title)
                .font(.headline)
                .foregroundStyle(.primary)
                .lineLimit(1)

            if card.isFromGuestLink { guestBadge }
            if card.showsSampleBadge { sampleBadge }

            Spacer(minLength: 8)

            if let statusIcon = card.statusIcon {
                Image(systemName: statusIcon)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(card.status.tint)
            }

            StatusBadge(status: card.status, compact: true)

            if density == .compact {
                Image(systemName: "chevron.right")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(.tertiary)
            }
        }
    }

    @ViewBuilder
    private var appContent: some View {
        switch card.template {
        case .list:
            appListRows
        case .progress:
            appValue
            if let progress = card.progressValue {
                ProgressView(value: progress)
                    .tint(card.status.tint)
            }
            if let subtitle = card.subtitle {
                appSubtitle(subtitle)
            }
        case .chart:
            appValue
            if let subtitle = card.subtitle {
                appSubtitle(subtitle)
            }
            sparkline(height: density == .compact ? 56 : 110, lineWidth: 2.5)
        case .history:
            appValue
            if let subtitle = card.subtitle {
                appSubtitle(subtitle)
            }
            statusStrip(limit: 20, height: 18)
            if density != .compact {
                appListRows
            }
        case .breakdown:
            appValue
            if let subtitle = card.subtitle {
                appSubtitle(subtitle)
            }
            compositionBar(height: 20)
            if density != .compact {
                appBreakdownRows
            }
        case .summary, .action:
            appValue
            if let subtitle = card.subtitle {
                appSubtitle(subtitle)
            }
        }
    }

    private var appValue: some View {
        HStack(alignment: .firstTextBaseline, spacing: 5) {
            Text(card.value ?? "—")
                .font(.system(size: 48, weight: .semibold, design: .rounded))
                .minimumScaleFactor(0.6)
                .lineLimit(1)
            if let unit = card.unit {
                Text(unit)
                    .font(.title3.weight(.medium))
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func appSubtitle(_ subtitle: String) -> some View {
        Text(subtitle)
            .font(.body)
            .foregroundStyle(.secondary)
            .lineLimit(density == .compact ? 1 : 3)
    }

    @ViewBuilder
    private var appListRows: some View {
        if let items = card.items, !items.isEmpty {
            let fractions = RankedRows.fractions(for: items)
            VStack(spacing: 10) {
                ForEach(items.prefix(density == .compact ? 3 : 10)) { item in
                    HStack(spacing: 12) {
                        Text(item.title)
                            .font(.subheadline)
                            .lineLimit(1)
                        Spacer(minLength: 8)
                        if let value = item.value {
                            Text("\(value)\(item.unit ?? "")")
                                .font(.subheadline.weight(.semibold))
                                .foregroundStyle(item.status?.tint ?? .primary)
                        }
                    }
                    .padding(.vertical, 3)
                    .padding(.horizontal, 6)
                    .background(alignment: .leading) {
                        if let fraction = fractions?[item.id] {
                            RankedRowBar(fraction: fraction, tint: item.status?.tint ?? card.status.tint)
                        }
                    }
                }
            }
        } else {
            Text("No items")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
    }

    @ViewBuilder
    private var appControls: some View {
        let actions = card.actions ?? []
        if (!actions.isEmpty && appActionHandler != nil) || card.deepLink != nil {
            Divider()

            VStack(spacing: 10) {
                if let appActionHandler {
                    ForEach(actions) { action in
                        Button {
                            appActionHandler(action)
                        } label: {
                            Label(action.label, systemImage: actionIcon(action))
                                .font(.body.weight(.semibold))
                                .frame(maxWidth: .infinity)
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(action.role == .destructive ? .red : card.status.tint)
                        .controlSize(.large)
                    }
                }

                if let deepLink = card.deepLink {
                    Link(destination: deepLink) {
                        Label("Open link", systemImage: "arrow.up.forward.app")
                            .font(.body.weight(.semibold))
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.bordered)
                    .tint(card.status.tint)
                    .controlSize(.large)
                }
            }
        }
    }

    private var appBackground: some ShapeStyle {
        LinearGradient(
            colors: [
                card.status.tint.opacity(0.12),
                Color.primary.opacity(0.055)
            ],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
    }

    private func actionIcon(_ action: ActionDefinition) -> String {
        action.role == .destructive ? "exclamationmark.triangle.fill" : "bolt.fill"
    }

    /// Value plus subtitle above a plot. The subtitle carries what the missing
    /// axis labels would have said ("last 10 days"), so it stays on chart cards
    /// even where `summary` drops it for space.
    private var chartHeadline: some View {
        VStack(alignment: .leading, spacing: 2) {
            bigValue
            if let subtitle = card.subtitle {
                Text(subtitle)
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
        }
    }

    @ViewBuilder
    private func compositionBar(height: CGFloat) -> some View {
        if let items = card.items, !items.isEmpty {
            CompositionBarView(items: items, tint: card.status.tint, height: height)
        }
    }

    /// A key for the bar, in the bar's own order. Each row shows the item's own
    /// `value` when it has one and the computed share otherwise, so a publisher
    /// can label segments in its own units without restating the percentages.
    @ViewBuilder
    private func breakdownLegend(max limit: Int) -> some View {
        let shares = CompositionBarView.shares(of: card.items ?? [])
        if limit > 0 && !shares.isEmpty {
            VStack(alignment: .leading, spacing: 3) {
                ForEach(Array(shares.prefix(limit).enumerated()), id: \.element.item.id) { index, entry in
                    HStack(spacing: 5) {
                        Circle()
                            .fill(CompositionBarView.tint(for: entry.item, index: index, base: card.status.tint))
                            .frame(width: 6, height: 6)
                        Text(entry.item.title)
                            .font(.caption2)
                            .lineLimit(1)
                        Spacer(minLength: 4)
                        Text(legendValue(entry.item, share: entry.share))
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
    }

    @ViewBuilder
    private var appBreakdownRows: some View {
        let shares = CompositionBarView.shares(of: card.items ?? [])
        if shares.isEmpty {
            Text("No items")
                .font(.subheadline)
                .foregroundStyle(.secondary)
        } else {
            VStack(spacing: 10) {
                ForEach(Array(shares.enumerated()), id: \.element.item.id) { index, entry in
                    HStack(spacing: 10) {
                        Circle()
                            .fill(CompositionBarView.tint(for: entry.item, index: index, base: card.status.tint))
                            .frame(width: 8, height: 8)
                        Text(entry.item.title)
                            .font(.subheadline)
                            .lineLimit(1)
                        Spacer(minLength: 8)
                        Text(legendValue(entry.item, share: entry.share))
                            .font(.subheadline.weight(.semibold))
                    }
                }
            }
        }
    }

    private func legendValue(_ item: DashboardItem, share: Double) -> String {
        if let value = item.value { return "\(value)\(item.unit ?? "")" }
        return "\(Int((share * 100).rounded()))%"
    }

    /// Nothing is drawn without items, the way `chart` draws nothing without a
    /// series — the headline value carries the card on its own.
    @ViewBuilder
    private func statusStrip(limit: Int, height: CGFloat) -> some View {
        if let items = card.items, !items.isEmpty {
            StatusStripView(items: items, limit: limit, height: height)
        }
    }

    /// Nothing is drawn when the series is missing or too short to be a trend;
    /// the card's headline value carries it instead.
    @ViewBuilder
    private func sparkline(height: CGFloat, lineWidth: CGFloat = 2) -> some View {
        if let chart = card.chart, chart.isRenderable {
            SparklineView(chart: chart, tint: card.status.tint, lineWidth: lineWidth)
                .frame(maxWidth: .infinity)
                .frame(height: height)
        }
    }

    private var actionSummary: some View {
        VStack(alignment: .leading, spacing: 2) {
            bigValue
            if let subtitle = card.subtitle {
                Text(subtitle)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(2)
            }
        }
    }

    @ViewBuilder
    private func listRows(max: Int) -> some View {
        if let items = card.items, !items.isEmpty {
            let fractions = RankedRows.fractions(for: items)
            VStack(alignment: .leading, spacing: 4) {
                ForEach(items.prefix(max)) { item in
                    HStack {
                        Text(item.title).font(.caption).lineLimit(1)
                        Spacer()
                        if let v = item.value {
                            Text("\(v)\(item.unit ?? "")")
                                .font(.caption)
                                .foregroundStyle(item.status?.tint ?? .primary)
                        }
                    }
                    .padding(.horizontal, 3)
                    .background(alignment: .leading) {
                        if let fraction = fractions?[item.id] {
                            RankedRowBar(fraction: fraction, tint: item.status?.tint ?? card.status.tint)
                        }
                    }
                }
            }
        } else {
            Text("No items").font(.caption2).foregroundStyle(.secondary)
        }
    }

    @ViewBuilder
    private func actionButtons(max: Int) -> some View {
        #if canImport(WidgetKit)
        if max <= 0 || widgetRenderingMode != .fullColor {
            EmptyView()
        } else if let actions = card.actions, !actions.isEmpty {
            VStack(alignment: .leading, spacing: 4) {
                ForEach(actions.prefix(max)) { action in
                    if action.isSafeFromWidget {
                        Button(intent: RunDashboardActionIntent(actionId: action.id, cardId: card.id)) {
                            Text(action.label)
                                .font(.caption)
                                .lineLimit(1)
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .buttonStyle(.borderedProminent)
                    } else if let deepLink = card.deepLink {
                        Link(destination: deepLink) {
                            Text(action.label)
                                .font(.caption)
                                .lineLimit(1)
                                .frame(maxWidth: .infinity, alignment: .leading)
                        }
                        .buttonStyle(.borderedProminent)
                    }
                }
            }
        }
        #else
        EmptyView()
        #endif
    }

}

extension DashboardCard {
    var progressValue: Double? {
        // An explicit `progress` wins on every template, and frees `value` to be
        // the display string it is everywhere else on the card.
        if let progress { return min(max(progress, 0), 1) }
        switch template {
        case .progress:
            // How a progress card said it before `progress` existed: the
            // fraction parsed out of `value`, with anything above 1 read as a
            // percentage. Kept so cards from producers that predate the field
            // keep drawing their bar.
            guard let v = value, let d = Double(v) else { return nil }
            return d > 1 ? d / 100 : d
        case .chart:
            // The circular accessory is a gauge and has no room for a plot. The
            // latest point, placed in the series' own range, is the only needle
            // position that means anything for a chart card.
            return chart?.normalizedPoints.last
        default:
            return nil
        }
    }

    /// Whether `value` is a label rather than the fraction itself. Only true
    /// once a card sends `progress`, which is what lets a progress card show a
    /// bar and a headline number at the same time.
    var progressValueIsLabel: Bool {
        progress != nil && value != nil
    }
}

public struct CardFallbackView: View {
    public enum Reason {
        case noCardSelected
        case noCachedData
        case stale(Date)
        case filtered(String)
        case error(String)
    }

    public let reason: Reason
    public init(reason: Reason) { self.reason = reason }

    public var body: some View {
        VStack(spacing: 4) {
            Image(systemName: iconName)
                .font(.title3)
                .foregroundStyle(.secondary)
            Text(title).font(.caption).foregroundStyle(.secondary)
            if let detail { Text(detail).font(.caption2).foregroundStyle(.tertiary).multilineTextAlignment(.center) }
        }
        .padding(8)
    }

    private var iconName: String {
        switch reason {
        case .noCardSelected: return "square.dashed"
        case .noCachedData: return "icloud.slash"
        case .stale: return "clock.badge.exclamationmark"
        case .filtered: return "line.3.horizontal.decrease.circle"
        case .error: return "exclamationmark.triangle"
        }
    }

    private var title: String {
        switch reason {
        case .noCardSelected: return "Pick a card"
        case .noCachedData: return "No data"
        case .stale: return "Stale"
        case .filtered: return "No matching cards"
        case .error: return "Error"
        }
    }

    private var detail: String? {
        switch reason {
        case .noCardSelected: return "Long-press to configure."
        case .noCachedData: return "Open 00Widget and refresh."
        case .stale(let d): return "Updated \(d.formatted(.relative(presentation: .named)))"
        case .filtered(let filter): return "No cached cards match \(filter)."
        case .error(let m): return m
        }
    }
}
